-- Calorie tracker schema and seed data.

create table if not exists foods (
  id bigint generated by default as identity primary key,
  name text not null unique,
  calories integer not null check (calories > 0),
  default_portion text not null,
  category text not null
);

create table if not exists daily_logs (
  id bigint generated by default as identity primary key,
  food_id bigint references foods(id) on delete set null,
  custom_name text,
  custom_calories integer,
  timestamp timestamptz not null default now(),
  constraint daily_logs_source_check
    check (
      food_id is not null
      or (custom_name is not null and custom_calories is not null and custom_calories > 0)
    )
);

create index if not exists daily_logs_timestamp_idx on daily_logs (timestamp desc);
create index if not exists daily_logs_food_id_idx on daily_logs (food_id);

alter table foods enable row level security;
alter table daily_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'foods' and policyname = 'Public read foods'
  ) then
    create policy "Public read foods"
      on foods
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'daily_logs' and policyname = 'Public read logs'
  ) then
    create policy "Public read logs"
      on daily_logs
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'daily_logs' and policyname = 'Public insert logs'
  ) then
    create policy "Public insert logs"
      on daily_logs
      for insert
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'daily_logs' and policyname = 'Public delete logs'
  ) then
    create policy "Public delete logs"
      on daily_logs
      for delete
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'daily_logs' and policyname = 'Public update logs'
  ) then
    create policy "Public update logs"
      on daily_logs
      for update
      using (true)
      with check (true);
  end if;
end
$$;

insert into foods (name, calories, default_portion, category) values
  ('High-Protein Overnight Oats', 380, '50g oats, 200ml milk, 1 scoop protein, 100g Greek yogurt', 'Morning / Breakfast / Pre-Workout'),
  ('Morning Tea', 70, 'With Stevia / zero-cal sweetener and 200ml milk', 'Morning / Breakfast / Pre-Workout'),
  ('Parle-G Biscuits', 120, '5 biscuits', 'Morning / Breakfast / Pre-Workout'),
  ('Boiled Eggs', 210, '3 eggs', 'Morning / Breakfast / Pre-Workout'),
  ('Apple', 95, '1 medium', 'Morning / Breakfast / Pre-Workout'),
  ('Caffè Nero Coffee', 10, 'Black or zero-cal', 'Morning / Breakfast / Pre-Workout'),
  ('Vegetable Soya Pulao', 430, 'Volumized with mixed veggies and soya chunks', 'Lunch (Fixed Daily Tiffin)'),
  ('Chobani Yogurt', 100, '1 cup', 'Lunch (Fixed Daily Tiffin)'),
  ('Homemade Dry Fruit Barfi', 170, '2 pieces', 'Lunch (Fixed Daily Tiffin)'),
  ('Protein Shake', 130, '1 scoop', 'Lunch (Fixed Daily Tiffin)'),
  ('Air-Fried Chicken Breast', 330, '200g raw / 7oz', 'Dinner (Varied High-Protein Rotation)'),
  ('Cooked White Rice', 100, '75g', 'Dinner (Varied High-Protein Rotation)'),
  ('Cooked White Rice (veg portion)', 130, '100g', 'Dinner (Varied High-Protein Rotation)'),
  ('Cooked Dal', 100, '100g', 'Dinner (Varied High-Protein Rotation)'),
  ('Cooked Dal (veg portion)', 200, '200g', 'Dinner (Varied High-Protein Rotation)'),
  ('Whole Wheat Roti', 90, '1 piece', 'Dinner (Varied High-Protein Rotation)'),
  ('Soya Chunks', 170, '50g dry, boiled', 'Dinner (Varied High-Protein Rotation)'),
  ('Whole Egg Bhurji', 330, '4 eggs cooked', 'Dinner (Varied High-Protein Rotation)'),
  ('Whole Wheat Bread', 240, '3 slices', 'Dinner (Varied High-Protein Rotation)'),
  ('Air-Fried Mixed Veggies', 50, 'Massive portion', 'Dinner (Varied High-Protein Rotation)')
on conflict (name) do nothing;