import type { FoodCategory, FoodItem } from '@/lib/types';

export const dailyCalorieTarget = {
  minimum: 1800,
  maximum: 2100,
};

export const mealCatalog: FoodCategory[] = [
  {
    name: 'Morning / Breakfast / Pre-Workout',
    description: 'Fast, high-compliance morning rotation for clean tapping.',
    items: [
      {
        id: 1,
        name: 'High-Protein Overnight Oats',
        calories: 380,
        protein_g: 30,
        carbs_g: 38,
        fat_g: 12,
        default_portion: '50g oats, 200ml milk, 1 scoop protein, 100g Greek yogurt',
        category: 'Morning / Breakfast / Pre-Workout',
      },
      {
        id: 2,
        name: 'Morning Tea',
        calories: 70,
        protein_g: 2,
        carbs_g: 9,
        fat_g: 2,
        default_portion: 'With Stevia / zero-cal sweetener and 200ml milk',
        category: 'Morning / Breakfast / Pre-Workout',
      },
      {
        id: 3,
        name: 'Parle-G Biscuits',
        calories: 120,
        protein_g: 2,
        carbs_g: 18,
        fat_g: 4,
        default_portion: '5 biscuits',
        category: 'Morning / Breakfast / Pre-Workout',
      },
      {
        id: 4,
        name: 'Boiled Eggs',
        calories: 210,
        protein_g: 19,
        carbs_g: 2,
        fat_g: 14,
        default_portion: '3 eggs',
        category: 'Morning / Breakfast / Pre-Workout',
      },
      {
        id: 5,
        name: 'Apple',
        calories: 95,
        protein_g: 0,
        carbs_g: 25,
        fat_g: 0,
        default_portion: '1 medium',
        category: 'Morning / Breakfast / Pre-Workout',
      },
      {
        id: 6,
        name: 'Caffè Nero Coffee',
        calories: 10,
        protein_g: 0,
        carbs_g: 2,
        fat_g: 0,
        default_portion: 'Black or zero-cal',
        category: 'Morning / Breakfast / Pre-Workout',
      },
    ],
  },
  {
    name: 'Lunch (Fixed Daily Tiffin)',
    description: 'Your structured midday stack, tuned for consistency.',
    items: [
      {
        id: 7,
        name: 'Vegetable Soya Pulao',
        calories: 430,
        protein_g: 18,
        carbs_g: 58,
        fat_g: 12,
        default_portion: 'Volumized with mixed veggies and soya chunks',
        category: 'Lunch (Fixed Daily Tiffin)',
      },
      {
        id: 8,
        name: 'Chobani Yogurt',
        calories: 100,
        protein_g: 11,
        carbs_g: 7,
        fat_g: 2,
        default_portion: '1 cup',
        category: 'Lunch (Fixed Daily Tiffin)',
      },
      {
        id: 9,
        name: 'Homemade Dry Fruit Barfi',
        calories: 170,
        protein_g: 4,
        carbs_g: 18,
        fat_g: 9,
        default_portion: '2 pieces',
        category: 'Lunch (Fixed Daily Tiffin)',
      },
      {
        id: 10,
        name: 'Protein Shake',
        calories: 130,
        protein_g: 25,
        carbs_g: 4,
        fat_g: 2,
        default_portion: '1 scoop',
        category: 'Lunch (Fixed Daily Tiffin)',
      },
    ],
  },
  {
    name: 'Dinner (Varied High-Protein Rotation)',
    description: 'Dinner blocks are modular so you can assemble the plate quickly.',
    items: [
      {
        id: 11,
        name: 'Air-Fried Chicken Breast',
        calories: 330,
        protein_g: 62,
        carbs_g: 0,
        fat_g: 7,
        default_portion: '200g raw / 7oz',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 12,
        name: 'Cooked White Rice',
        calories: 100,
        protein_g: 2,
        carbs_g: 22,
        fat_g: 0,
        default_portion: '75g',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 13,
        name: 'Cooked White Rice (veg portion)',
        calories: 130,
        protein_g: 2,
        carbs_g: 28,
        fat_g: 0,
        default_portion: '100g',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 14,
        name: 'Cooked Dal',
        calories: 100,
        protein_g: 7,
        carbs_g: 13,
        fat_g: 2,
        default_portion: '100g',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 15,
        name: 'Cooked Dal (veg portion)',
        calories: 200,
        protein_g: 14,
        carbs_g: 26,
        fat_g: 4,
        default_portion: '200g',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 16,
        name: 'Whole Wheat Roti',
        calories: 90,
        protein_g: 3,
        carbs_g: 18,
        fat_g: 2,
        default_portion: '1 piece',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 17,
        name: 'Soya Chunks',
        calories: 170,
        protein_g: 26,
        carbs_g: 12,
        fat_g: 1,
        default_portion: '50g dry, boiled',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 18,
        name: 'Whole Egg Bhurji',
        calories: 330,
        protein_g: 28,
        carbs_g: 4,
        fat_g: 22,
        default_portion: '4 eggs cooked',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 19,
        name: 'Whole Wheat Bread',
        calories: 240,
        protein_g: 9,
        carbs_g: 42,
        fat_g: 4,
        default_portion: '3 slices',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
      {
        id: 20,
        name: 'Air-Fried Mixed Veggies',
        calories: 50,
        protein_g: 2,
        carbs_g: 8,
        fat_g: 1,
        default_portion: 'Massive portion',
        category: 'Dinner (Varied High-Protein Rotation)',
      },
    ],
  },
];

export const mealCatalogByName = mealCatalog.flatMap((group) => group.items).reduce<Record<string, FoodItem>>((lookup, item) => {
  lookup[item.name] = item;
  return lookup;
}, {} as Record<string, FoodItem>);